# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FFRNMap' do

  pod 'React', :path => './node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
    
  ]

end
